// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("calendar.timezone.local", "Asia/Seoul");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1743587518);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241211204238");
user_pref("extensions.lastAppVersion", "115.18.0");
user_pref("extensions.lastPlatformVersion", "115.18.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"ffb34738-c9e1-463b-af26-9bce773b6f0f\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.startup.last_success", 1743587516);
user_pref("toolkit.telemetry.cachedClientID", "06845ba7-c89e-47d5-b171-71026c590105");
user_pref("toolkit.telemetry.previousBuildID", "20241211204238");
